**Ubuntu 20.04 Test: 25/07/2020**
Simple bugfix: frontend\views\productsubcategory\index.php:
Error: Class Arrayhelper not found.
Solution: use yii\helpers\Arrayhelper

Simple bugfix: frontend\config\main.php
Error: Url's eg. Url=> (['product/index'])in frontend\views\layouts\main.php not including DocumentRoot from conf under etc\Apache2\rr.conf
Solution 1: Remove BaseUrl => '/' from frontend\config\main.php
Solution 2: Add Url::to([....]) to (['quicknote/create']) in frontend\views\layouts\main.php

Simple Bugfix: frontend\components\Utilities line 393
Error: GroupBy command causing error;
Solution: Remove

Error: frontend/Runtime folder not writable
Solution: Alter composer.json. Emulate yiipowered's composer.json

Simple Bugfix: frontend/modules/backup/views/backuper/dump

Improvement: Introduce Modals (ie. popupscreen) on product, productsubcategory, and productcategory
Improvement: Added loading and loader gif for the popup Modal.
Improvement: Removed dummy test backups under mysqlbackup directory.